### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by pburtchaell** [mike-schultz/materialette#10]
When compared to the icon on the website, the icon appears too large on macOS v10.12.
## Expected Behavior

The icon size is similar in size to other status bar icons.
## Actual Behavior

The icon size is larger than other status bar icons.

![screen shot 2016-10-17 at 12 32 57 am](https://cloud.githubusercontent.com/assets/3857324/19426344/5d0661fe-9401-11e6-8e4d-8a990cc7840e.png)

**Comment by mike-schultz** [comment]
Fixed. see 3331e98
