### ISSUE TITLE
Resizable window

### ISSUE THREAD

**Issue by shinr** [mike-schultz/materialette#15]
I was checking materialette out and found out that you are able to resize the window.  I doubt this is intended behavior at this stage, so I thought I'd let you know.  This is on Windows 10.

![resize](https://cloud.githubusercontent.com/assets/9823687/19470267/72f7f9c4-9527-11e6-9cbf-0cf6fd0b1312.png)

**Comment by amitmerchant1990** [comment]
Need to add `resizable` : `false` in Browser instance options.

**Comment by mike-schultz** [comment]
Fixed. Thanks!
