### ISSUE TITLE
Bug: Hit CMD+V in materialette, cannot copy colors anymore

### ISSUE THREAD

**Issue by bildlich** [mike-schultz/materialette#18]
I came across this issue on OS X 10.11.6 

How to reproduce:
1. Click tray icon to reveal Materialette
2. Click color field to copy color (e.g. #000000)
3. Open empty text file, hit CMD+V to paste: works perfectly ✔︎
4. Reveal Materialette again
5. **Hit CMD+V as if to paste something in Materialette**
6. Click another color field to copy another color (e.g. #ffffff)
7. Go back to text file, hit CMD+V: #000000 is pasted, the new color is not in the clipboard ✗
8. All subsequent attempts to copy a color from Materialette fail until I restart the program

**Comment by mike-schultz** [comment]
Fixed! I'm using an offscreen `<textarea>` to perform copy&paste, but once that gets modified by the user (a paste action), it becomes unmodifiable from javascript. Fixed that easily by making it readonly.
