### ISSUE TITLE
No option to close/quit the app

### ISSUE THREAD

**Issue by dstock48** [mike-schultz/materialette#2]
Once opened, I don't see any option to quit the app when its no longer needed.

I'd recommend adding a right-click menu on the menubar icon with options like 'About' and 'Quit'.

**Comment by mike-schultz** [comment]
Thanks for the suggestion. I'll add that in there today...as for now cmd + q works at least!

**Comment by mike-schultz** [comment]
Now available in [v1.1.0](https://github.com/mike-schultz/materialette/releases/tag/1.1.0)!
