### ISSUE TITLE
Fail to build in OSX, can we add node versions and possibly yarn.lock

### ISSUE THREAD

**Issue by dvidsilva** [mike-schultz/materialette#20]
Hi, it would be good to use [nvm](https://github.com/creationix/nvm/blob/master/README.markdown) to keep a consistent version of node and npm, that will make it easier to run locally and contribute.

Ideally using yarn instead of npm to install the dependencies would be good too, it will allow to save the version of the dependencies and in that way be able to run it better and more constantly in different environments. 

I could give it a shot, and get it to run in latest node.

I'm using 
```
node --version
v6.4.0
```

and 
```
npm --version
3.10.3
```

**Comment by dvidsilva** [comment]
Nevermind I got it to run, still would be nicer to use yarn and nvm :D

**Comment by mike-schultz** [comment]
Glad you got it working. What was the issue? I've been meaning to take a look into using yarn... PRs are also welcome :)
