### ISSUE TITLE
Use system fonts

### ISSUE THREAD

**Issue by mn113** [mike-schultz/materialette#4]
Does the applet have to make a network request to fonts.googleapis.com?

**Comment by mike-schultz** [comment]
You're right - It's probably overkill for such small font sizes and text. I was using Roboto to keep consistent with the Google theme, but Helvetica/Arial look pretty close. Changed in: 07eab47 and will be out in the next release!

**Comment by wachunei** [comment]
I'd recommend using this font-family stack, it uses macOS default font.

https://github.com/wachunei/wifiuc-menubar/blob/master/source/app/styles/style.css#L5

**Comment by mike-schultz** [comment]
@wachunei Thanks for the suggestion. Added! 4f9fa60
